services:
  - type: web
    name: correios-rastreio-api
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
